### ISSUE TITLE
a teeny tiny bug

### ISSUE THREAD

**Issue by gkhdfdfg** [bakabakabakabakabaka/BW11V2#3]
the thing works! but... everytime i update it is downloading the whole OS again (like when we update from windows 10 to 11). It takes up a lot of internet and i'm on a budget. so pls correct it | _note : i'm new to github so if any mistakes, pls accept my apology_ |

before microsoft started to do checks, the updates were short. now it is looooooooooooooooooooooooooooooong

Windows 11 Build 22478 (DEV)

I hope it'll be corrected soon. thanks for reading this!

**Comment by nebula-neru** [comment]
I'm unable to fix this, since Windows Update does that normally. If you need an alternative use this [Click me](https://github.com/AveYo/MediaCreationTool.bat/blob/main/MCT/Skip_TPM_Check_on_Dynamic_Update_v2.cmd)
You won't have to restart the download anymore. <3

**Comment by gkhdfdfg** [comment]
oh ok
Thanks!
